import { memo, useMemo } from 'react'
import {
  EdgeLabelRenderer,
  type EdgeProps,
  type Edge,
} from '@xyflow/react'
import rough from 'roughjs'
import { useT } from '~/hooks/useTranslation'
import { getResolvedColor } from '~/lib/theme-colors'
import { useRecipeFlowStore } from '~/stores/recipe-flow-store'

interface RecipeEdgeData extends Record<string, unknown> {
  scheduleTimeRatio: number
  scheduleQtyRatio: number
  label?: string
  curvature?: number
}

/** Extract SVG child elements generated by Rough.js as serialized HTML strings */
function roughPathToSvg(
  pathData: string,
  options: {
    stroke: string
    strokeWidth: number
    roughness: number
    bowing: number
    strokeLineDash?: number[]
  },
): string {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  const rc = rough.svg(svg)
  const node = rc.path(pathData, {
    stroke: options.stroke,
    strokeWidth: options.strokeWidth,
    roughness: options.roughness,
    bowing: options.bowing,
    fill: 'none',
    strokeLineDash: options.strokeLineDash,
  })
  return node.innerHTML
}

/** Generate rough line SVG markup */
function roughLineToSvg(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  options: { stroke: string; strokeWidth: number; roughness: number },
): string {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  const rc = rough.svg(svg)
  const node = rc.line(x1, y1, x2, y2, {
    stroke: options.stroke,
    strokeWidth: options.strokeWidth,
    roughness: options.roughness,
    fill: 'none',
  })
  return node.innerHTML
}

function RecipeFlowEdgeInner({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  data,
}: EdgeProps<Edge<RecipeEdgeData>>) {
  const t = useT()
  const updateEdgeCurvature = useRecipeFlowStore((s) => s.updateEdgeCurvature)
  const curvature = data?.curvature ?? 0.25

  // Compute custom bezier path with curvature
  const controlPointOffset = Math.abs(targetY - sourceY) * curvature
  const edgePath = `M ${sourceX} ${sourceY} C ${sourceX} ${sourceY + controlPointOffset}, ${targetX} ${targetY - controlPointOffset}, ${targetX} ${targetY}`

  // Label position at midpoint of bezier
  const labelX = (sourceX + targetX) / 2
  const labelY = (sourceY + targetY) / 2

  const timeRatio = data?.scheduleTimeRatio ?? 1
  const qtyRatio = data?.scheduleQtyRatio ?? 1
  const hasCustomValues = timeRatio < 1 || qtyRatio < 1 || data?.label
  const isDashed = timeRatio < 1

  // Compute arrowhead points from bezier tangent at target
  const arrowMarkup = useMemo(() => {
    const dx = targetX - (targetX + (sourceX - targetX) * 0.1)
    const dy = targetY - (targetY + (sourceY - targetY) * 0.1)
    const angle = Math.atan2(dy, dx)
    const arrowLen = 24
    const arrowAngle = Math.PI / 4

    const x1 = targetX - arrowLen * Math.cos(angle - arrowAngle)
    const y1 = targetY - arrowLen * Math.sin(angle - arrowAngle)
    const x2 = targetX - arrowLen * Math.cos(angle + arrowAngle)
    const y2 = targetY - arrowLen * Math.sin(angle + arrowAngle)

    if (typeof document === 'undefined') return ''

    const color = getResolvedColor('canvas-edge')
    const line1 = roughLineToSvg(x1, y1, targetX, targetY, {
      stroke: color,
      strokeWidth: 5,
      roughness: 2.0,
    })
    const line2 = roughLineToSvg(x2, y2, targetX, targetY, {
      stroke: color,
      strokeWidth: 5,
      roughness: 2.0,
    })
    return line1 + line2
  }, [sourceX, sourceY, targetX, targetY])

  // Generate rough path SVG
  const roughEdgeMarkup = useMemo(() => {
    if (typeof document === 'undefined') return ''
    const color = getResolvedColor('canvas-edge')
    return roughPathToSvg(edgePath, {
      stroke: color,
      strokeWidth: 3.5,
      roughness: 1.8,
      bowing: 2,
      strokeLineDash: isDashed ? [8, 5] : undefined,
    })
  }, [edgePath, isDashed])

  return (
    <>
      {/* Rough.js hand-drawn edge path */}
      <g dangerouslySetInnerHTML={{ __html: roughEdgeMarkup }} />

      {/* Rough.js hand-drawn arrowhead */}
      <g dangerouslySetInnerHTML={{ __html: arrowMarkup }} />

      {/* Invisible wider click-target path */}
      <path
        d={edgePath}
        fill="none"
        stroke="transparent"
        strokeWidth={20}
        style={{ cursor: 'pointer' }}
      />

      {/* Reconnection grab areas */}
      <circle cx={sourceX} cy={sourceY} r={10} fill="transparent" style={{ cursor: 'crosshair' }} />
      <circle cx={targetX} cy={targetY} r={10} fill="transparent" style={{ cursor: 'crosshair' }} />

      {hasCustomValues && (
        <EdgeLabelRenderer>
          <div
            className="absolute text-[9px] font-medium font-sketch px-1.5 py-0.5 rounded-full bg-card border border-border text-panel-header shadow-sm pointer-events-none"
            style={{
              transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
            }}
          >
            {data?.label || (timeRatio < 1 ? t("edge_time_at_pct", { pct: Math.round(timeRatio * 100) }) : t("edge_qty_at_pct", { pct: Math.round(qtyRatio * 100) }))}
          </div>
        </EdgeLabelRenderer>
      )}

      {/* Draggable curvature handle */}
      <EdgeLabelRenderer>
        <div
          className="absolute w-3 h-3 rounded-full bg-canvas-edge/40 hover:bg-canvas-edge/80 cursor-grab active:cursor-grabbing transition-colors"
          style={{
            transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
            pointerEvents: 'all',
          }}
          onMouseDown={(e) => {
            e.stopPropagation()
            e.preventDefault()
            const startY = e.clientY
            const startCurvature = curvature

            const onMouseMove = (ev: MouseEvent) => {
              const deltaY = ev.clientY - startY
              const newCurvature = Math.max(0.05, Math.min(1.5, startCurvature + deltaY * 0.003))
              updateEdgeCurvature(id, newCurvature)
            }

            const onMouseUp = () => {
              document.removeEventListener('mousemove', onMouseMove)
              document.removeEventListener('mouseup', onMouseUp)
            }

            document.addEventListener('mousemove', onMouseMove)
            document.addEventListener('mouseup', onMouseUp)
          }}
        />
      </EdgeLabelRenderer>
    </>
  )
}

export const RecipeFlowEdge = memo(RecipeFlowEdgeInner)
