import type { Recipe } from '@commons/types/recipe'

/**
 * Pane Casareccio con Biga 80%
 *
 * Total dough target: ~1000g (2 panetti da 500g)
 * Hydration: 65%
 * Biga: 80% of total dough
 *
 * Calculations:
 *   totalFlour = totalDough / (1 + hyd/100) = 1000 / 1.65 ≈ 606g
 *   totalLiquid = 606 * 0.65 ≈ 394g
 *   pfWeight = 1000 * 0.80 = 800g
 *   pfFlour = 800 / (1 + 0.44) ≈ 555.6g
 *   pfWater = 555.6 * 0.44 ≈ 244.4g
 *   pfYeast = 555.6 * 0.01 ≈ 5.6g
 *   mainFlour = 606 - 555.6 ≈ 50.4g
 *   mainWater = 394 - 244.4 ≈ 149.6g
 */
export const RECIPE_2: Recipe = {
  meta: {
    name: "Pane Casareccio con Biga",
    author: "KitchenPizza",
    type: "pane",
    subtype: "pane_comune",
  },
  portioning: {
    mode: "ball",
    tray: {
      preset: "terrina_29",
      l: 29,
      w: 8.5,
      h: 9,
      material: "ci_lid",
      griglia: false,
      count: 1,
    },
    thickness: 0.6,
    ball: { weight: 500, count: 2 },
    targetHyd: 65, doughHours: 18, yeastPct: 0.22, saltPct: 2.3, fatPct: 3, preImpasto: null, preFermento: null,
  },
  ingredientGroups: ["Biga", "Impasto"],
  steps: [
    {
      id: "biga_prep",
      title: "Preparazione Biga",
      type: "pre_ferment",
      subtype: "biga",
      group: "Biga",
      baseDur: 15,
      restDur: 0,
      restTemp: null,
      deps: [],
      kneadMethod: null,
      desc: "Mescola farina, acqua fredda e lievito sbriciolato fino a ottenere una massa asciutta e sbriciolata (non un impasto liscio). Copri con pellicola.",
      flours: [{ id: 0, type: "gt_0_for", g: 555.5, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 244.5, temp: 18 }],
      extras: [],
      yeasts: [{ id: 0, type: "fresh", g: 5.5 }],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: {
        preFermentPct: 80,
        hydrationPct: 44,
        yeastType: "fresh",
        yeastPct: 1,
        fermentTemp: 18,
        fermentDur: 1080,
        roomTempDur: null,
        starterForm: null,
      },
    },
    {
      id: "biga_ferment",
      title: "Maturazione Biga",
      type: "rise",
      subtype: "ctrl18",
      group: "Biga",
      baseDur: 1080,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "biga_prep", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia fermentare a 18 °C per 16-24 ore. La biga è pronta quando è raddoppiata, ha un profumo alcolico e mostra crepe in superficie.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "ctrl18",
      ovenCfg: null,
      sourcePrep: "biga_prep",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "knead",
      title: "Impasto Finale",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 20,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "biga_ferment", wait: 1, grams: 1 }],
      kneadMethod: "hand",
      desc: "Spezza la biga in pezzi piccoli, aggiungila gradualmente all'impasto con farina, acqua e sale. Impasta fino a completo sviluppo del glutine.",
      flours: [{ id: 0, type: "gt_0_for", g: 50.5, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 149.5, temp: null }],
      extras: [],
      yeasts: [],
      salts: [{ id: 0, type: "sale_fino", g: 20 }],
      sugars: [{ id: 0, type: "malto_d", g: 2.4 }],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "r1",
      title: "1ª Lievitazione",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 60,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "knead", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia lievitare a temperatura ambiente per circa 1 ora, fino al raddoppio.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "biga_prep",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "shape",
      title: "Formatura",
      type: "shape",
      subtype: null,
      group: "Impasto",
      baseDur: 10,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r1", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Dividi l'impasto in 2 pezzi da ~500g. Forma delle pagnotte tonde o ovali.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: 2,
      preFermentCfg: null,
    },
    {
      id: "r2",
      title: "2ª Lievitazione",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 45,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "shape", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia lievitare le pagnotte coperte per 45 minuti.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "biga_prep",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "scoring",
      title: "Tagli",
      type: "pre_bake",
      subtype: "scoring",
      group: "Impasto",
      baseDur: 3,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r2", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Incidi la superficie con un coltello o una lametta.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "bake",
      title: "Cottura",
      type: "bake",
      subtype: null,
      group: "Impasto",
      baseDur: 35,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "scoring", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forno preriscaldato a 230°C con vapore. Dopo 15 minuti riduci a 200°C.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: {
        panType: "ci_lid",
        ovenType: "electric",
        ovenMode: "static",
        temp: 230,
        cieloPct: 50,
        shelfPosition: 2,
      },
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "done",
      title: "Buon Appetito!",
      type: "done",
      subtype: null,
      group: "Impasto",
      baseDur: 0,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "bake", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia raffreddare su una griglia per almeno 30 minuti prima di tagliare.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
  ],
}
