import type { Recipe } from '@commons/types/recipe'

export const RECIPE_1: Recipe = {
  meta: {
    name: "Shokupan 食パン",
    author: "Cucchiaio d'Argento",
    type: "pane",
    subtype: "shokupan",
    locale: "it",
  },
  portioning: {
    mode: "tray",
    tray: {
      preset: "terrina_29",
      l: 29,
      w: 8.5,
      h: 9,
      material: "ci_lid",
      griglia: false,
      count: 1,
    },
    thickness: 0.6,
    ball: { weight: 250, count: 3 },
    targetHyd: 81, doughHours: 18, yeastPct: 0.22, saltPct: 2.3, fatPct: 3, preImpasto: null, preFermento: null, flourMix: [], autoCorrect: false, reasoningLevel: 'medium',
  },
  ingredientGroups: ["Tangzhong", "Impasto", "Finitura"],
  steps: [
    {
      id: "roux",
      title: "Tangzhong (Roux)",
      type: "pre_dough",
      subtype: "tangzhong",
      group: "Tangzhong",
      baseDur: 5,
      restDur: 0,
      restTemp: null,
      deps: [],
      kneadMethod: null,
      desc: "Mescola farina e acqua. Cuoci fino a gel denso.",
      flours: [{ id: 0, type: "gt_00_deb", g: 22.5, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 112, temp: null }],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "roux_cool",
      title: "Raffreddamento roux",
      type: "rest",
      subtype: null,
      group: "Tangzhong",
      baseDur: 30,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "roux", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia raffreddare completamente.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "knead",
      title: "Impastare",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 20,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "roux_cool", wait: 0.75, grams: 1 }],
      kneadMethod: "hand",
      desc: "Unisci roux, farina, zucchero, sale, miele, lievito, latte. Burro per ultimo.",
      flours: [{ id: 0, type: "gt_0_for", g: 315, temp: null }],
      liquids: [{ id: 0, type: "Latte freddo", g: 162, temp: 5 }],
      extras: [],
      yeasts: [{ id: 0, type: "fresh", g: 6.3 }],
      salts: [{ id: 0, type: "sale_fino", g: 7.2 }],
      sugars: [{ id: 0, type: "zucchero", g: 36 }, { id: 1, type: "miele", g: 6.3 }],
      fats: [{ id: 0, type: "burro", g: 45 }],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "r1a",
      title: "1ª lievitaz. — fase 1",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 120,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "knead", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia raddoppiare.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "r1b",
      title: "1ª lievitaz. — fase 2",
      type: "rise",
      subtype: "fridge",
      group: "Impasto",
      baseDur: 200,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r1a", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "In frigo per aromi e lavorabilità.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "fridge",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "shape",
      title: "Formare e arrotolare",
      type: "shape",
      subtype: null,
      group: "Impasto",
      baseDur: 15,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r1b", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Dividi, stendi, arrotola in cilindri.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: 3,
      preFermentCfg: null,
    },
    {
      id: "r2",
      title: "2ª lievitaz. in teglia",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 150,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "shape", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "In teglia imburrata fino al bordo.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "brush",
      title: "Spennellare",
      type: "pre_bake",
      subtype: "brush",
      group: "Finitura",
      baseDur: 5,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r2", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Tuorlo e latte.",
      flours: [],
      liquids: [],
      extras: [
        { id: 0, name: "Tuorlo d'uovo", g: 1, unit: "pz" },
        { id: 1, name: "Latte", g: 0, unit: "q.b." },
      ],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "bake",
      title: "Cottura",
      type: "bake",
      subtype: null,
      group: "Impasto",
      baseDur: 35,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "brush", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forno preriscaldato.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: {
        panType: "ci_lid",
        ovenType: "electric",
        ovenMode: "static",
        temp: 170,
        cieloPct: 50,
        shelfPosition: 1,
      },
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    {
      id: "done",
      title: "Buon Appetito!",
      type: "done",
      subtype: null,
      group: "Impasto",
      baseDur: 0,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "bake", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Sforna e intiepidisci.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
  ],
}

/** Total dough weight computed from the default recipe (sum of all flour, liquid, extra without unit, and yeast grams). */
export const BASE_DOUGH_WEIGHT: number = (() => {
  let t = 0
  for (const s of RECIPE_1.steps) {
    for (const f of s.flours) t += f.g
    for (const l of s.liquids) t += l.g
    for (const e of s.extras) if (!e.unit) t += e.g
    for (const y of s.yeasts) t += y.g
  }
  return t
})()
