/**
 * Pizza Margherita — 3 layers (Impasto, Sugo, Assemblaggio).
 *
 * A classic multi-layer recipe demonstrating cross-layer dependencies:
 * the dough and sauce layers run in parallel, then feed into the assembly layer.
 */

import type { RecipeV3 } from '@commons/types/recipe-layers'

export const RECIPE_ML_MARGHERITA: RecipeV3 = {
  version: 3,
  meta: {
    name: 'Pizza Margherita Classica',
    author: 'KitchenPizza Zero',
    type: 'pizza',
    subtype: 'napoletana',
    locale: 'it',
  },
  ingredientGroups: ['Impasto', 'Sugo', 'Assemblaggio'],
  layers: [
    // ── Layer 0: Impasto ──────────────────────────────────────
    {
      id: 'layer_impasto',
      type: 'impasto',
      subtype: 'pizza',
      variant: 'napoletana',
      name: 'Impasto',
      color: '#F59E0B',
      icon: '\u{1F35E}',
      position: 0,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'impasto',
        config: {
          mode: 'ball',
          tray: { preset: 'teglia_40x30', l: 40, w: 30, h: 2, material: 'alu', griglia: false, count: 1 },
          ball: { weight: 250, count: 4 },
          thickness: 0.5,
          targetHyd: 65,
          doughHours: 24,
          yeastPct: 0.1,
          saltPct: 2.5,
          fatPct: 2,
          preImpasto: null,
          preFermento: null,
          flourMix: [],
          autoCorrect: false,
          reasoningLevel: 'medium',
        },
      },
      nodes: [
        {
          id: 'imp_dough',
          type: 'dough',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Impasto diretto',
            desc: 'Farina, acqua, sale, lievito',
            group: 'Impasto',
            baseDur: 20,
            restDur: 0,
            restTemp: null,
            flours: [{ id: 1, type: 'gt_00_deb', g: 600, temp: null }],
            liquids: [{ id: 1, type: 'water', g: 390, temp: 20 }],
            extras: [],
            yeasts: [{ id: 1, type: 'fresh', g: 0.6 }],
            salts: [{ id: 1, type: 'sale', g: 15 }],
            sugars: [],
            fats: [{ id: 1, type: 'olio_evo', g: 12 }],
            kneadMethod: 'hand',
          },
        },
        {
          id: 'imp_rise_room',
          type: 'rise',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Puntata a temperatura ambiente',
            desc: '2 ore a 22-24\u00B0C',
            group: 'Impasto',
            baseDur: 120,
            restDur: 0,
            restTemp: 23,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            riseMethod: 'room',
          },
        },
        {
          id: 'imp_rise_fridge',
          type: 'rise',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Maturazione in frigo',
            desc: '22 ore a 4\u00B0C',
            group: 'Impasto',
            baseDur: 1320,
            restDur: 0,
            restTemp: 4,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            riseMethod: 'fridge',
          },
        },
        {
          id: 'imp_shape',
          type: 'shape',
          subtype: null,
          position: { x: 0, y: 450 },
          lane: 'main',
          data: {
            title: 'Staglio e formatura',
            desc: 'Dividere in 4 panetti da 250g',
            group: 'Impasto',
            baseDur: 15,
            restDur: 60,
            restTemp: 23,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            shapeCount: 4,
          },
        },
      ],
      edges: [
        { id: 'e_imp_1', source: 'imp_dough', target: 'imp_rise_room', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_imp_2', source: 'imp_rise_room', target: 'imp_rise_fridge', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_imp_3', source: 'imp_rise_fridge', target: 'imp_shape', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Panificazione', isMain: true, origin: { type: 'user' } }],
    },

    // ── Layer 1: Sugo ─────────────────────────────────────────
    {
      id: 'layer_sugo',
      type: 'sauce',
      subtype: 'sugo',
      variant: 'pomodoro_fresco',
      name: 'Sugo pomodoro',
      color: '#EF4444',
      icon: '\u{1F345}',
      position: 1,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'sauce',
        config: {
          sauceType: 'pomodoro',
          targetVolume: 400,
          targetConsistency: 'medium',
          serving: 4,
          shelfLife: 3,
        },
      },
      nodes: [
        {
          id: 'sugo_ing',
          type: 'ingredient',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Pomodori San Marzano',
            desc: 'Pelati, 400g',
            group: 'Sugo',
            baseDur: 5,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [], fats: [],
            extras: [{ id: 1, name: 'Pomodori pelati', g: 400 }],
          },
        },
        {
          id: 'sugo_season',
          type: 'season',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Condimento',
            desc: 'Sale, olio, basilico fresco',
            group: 'Sugo',
            baseDur: 3,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], sugars: [],
            salts: [{ id: 1, type: 'sale', g: 4 }],
            fats: [{ id: 1, type: 'olio_evo', g: 15 }],
            extras: [{ id: 1, name: 'Basilico fresco', g: 5 }],
          },
        },
        {
          id: 'sugo_blend',
          type: 'blend',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Frullare',
            desc: 'Passare al frullatore ad immersione',
            group: 'Sugo',
            baseDur: 3,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
          },
        },
      ],
      edges: [
        { id: 'e_sugo_1', source: 'sugo_ing', target: 'sugo_season', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_sugo_2', source: 'sugo_season', target: 'sugo_blend', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Sugo', isMain: true, origin: { type: 'user' } }],
    },

    // ── Layer 2: Assemblaggio ─────────────────────────────────
    {
      id: 'layer_assembly',
      type: 'prep',
      subtype: 'base',
      variant: 'assemblaggio',
      name: 'Assemblaggio',
      color: '#8B5CF6',
      icon: '\u{1F355}',
      position: 2,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'prep',
        config: {
          prepType: 'assemblaggio',
          servings: 4,
          yield: 1000,
        },
      },
      nodes: [
        {
          id: 'asm_top',
          type: 'assemble',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Farcire le pizze',
            desc: 'Stendere impasto, sugo, mozzarella, basilico',
            group: 'Assemblaggio',
            baseDur: 10,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [], fats: [],
            extras: [
              { id: 1, name: 'Mozzarella di bufala', g: 400 },
              { id: 2, name: 'Basilico fresco', g: 10 },
            ],
            applicationMethod: 'topping',
            applicationTiming: 'pre_bake',
          },
        },
        {
          id: 'asm_bake',
          type: 'cook',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Cottura',
            desc: '450\u00B0C per 90 secondi',
            group: 'Assemblaggio',
            baseDur: 2,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            cookMethod: 'oven',
            cookTemp: 450,
          },
        },
        {
          id: 'asm_plate',
          type: 'plate',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Impiattare',
            desc: 'Filo d\'olio e basilico fresco',
            group: 'Assemblaggio',
            baseDur: 2,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [],
            fats: [{ id: 1, type: 'olio_evo', g: 10 }],
            extras: [{ id: 1, name: 'Basilico', g: 5 }],
          },
        },
      ],
      edges: [
        { id: 'e_asm_1', source: 'asm_top', target: 'asm_bake', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_asm_2', source: 'asm_bake', target: 'asm_plate', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Assemblaggio', isMain: true, origin: { type: 'user' } }],
    },
  ],

  crossEdges: [
    // Impasto shape -> Assembly topping
    {
      id: 'xedge_imp_shape__asm_top',
      sourceLayerId: 'layer_impasto',
      sourceNodeId: 'imp_shape',
      targetLayerId: 'layer_assembly',
      targetNodeId: 'asm_top',
      label: 'impasto pronto',
      data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 },
    },
    // Sugo blend -> Assembly topping
    {
      id: 'xedge_sugo_blend__asm_top',
      sourceLayerId: 'layer_sugo',
      sourceNodeId: 'sugo_blend',
      targetLayerId: 'layer_assembly',
      targetNodeId: 'asm_top',
      label: 'sugo pronto',
      data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 },
    },
  ],
}
