import type { Recipe } from '@commons/types/recipe'

/**
 * Treccia Bicolore con Poolish e Split/Join
 *
 * Poolish → Impasto base → SPLIT 50/50
 *   Ramo "Pomodoro": Impasto +pomodoro → Lievitazione → Formatura filone rosso
 *   Ramo "Basilico": Impasto +basilico → Lievitazione → Formatura filone verde
 * → JOIN (intreccio) → 2ª Lievitazione → Spennellatura → Cottura → Fine
 *
 * NOTE: Questo file usa il formato v1 (steps+deps). La divisione è rappresentata
 * con un nodo di tipo "split" e la riunione con un nodo di tipo "join".
 * Al caricamento verrà migrato a v2 (graph).
 */
export const RECIPE_4: Recipe = {
  meta: {
    name: "Treccia Bicolore Pomodoro e Basilico",
    author: "KitchenPizza",
    type: "pane",
    subtype: "pane_comune",
    locale: "it",
  },
  portioning: {
    mode: "ball",
    tray: { preset: "teglia_40x30", l: 40, w: 30, h: 2, material: "alu", griglia: false, count: 1 },
    ball: { weight: 415, count: 2 },
    thickness: 0.5,
    targetHyd: 60, doughHours: 18, yeastPct: 0.22, saltPct: 2.3, fatPct: 3, preImpasto: null, preFermento: null, flourMix: [], autoCorrect: false, reasoningLevel: 'medium',
  },
  ingredientGroups: ["Impasto"],
  steps: [
    // ── Poolish ──
    {
      id: "poolish",
      title: "Poolish",
      type: "pre_ferment",
      subtype: "poolish",
      group: "Impasto",
      baseDur: 15,
      restDur: 0,
      restTemp: null,
      deps: [],
      kneadMethod: null,
      desc: "Sciogli il lievito nell'acqua, aggiungi la farina e mescola. Copri e lascia fermentare 12h a 20°C.",
      flours: [{ id: 0, type: "gt_00_for", g: 200, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 200, temp: null }],
      extras: [],
      yeasts: [{ id: 0, type: "fresh", g: 2 }],
      salts: [], sugars: [], fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: {
        preFermentPct: 48, hydrationPct: 100, yeastType: "fresh", yeastPct: 1,
        fermentTemp: 20, fermentDur: 720, roomTempDur: null, starterForm: null,
      },
    },
    // ── Fermentazione Poolish ──
    {
      id: "poolish_ferm",
      title: "Fermentazione Poolish",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 720,
      restDur: 0, restTemp: null,
      deps: [{ id: "poolish", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia fermentare il poolish coperto a 20°C per 12 ore.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: "room", ovenCfg: null, sourcePrep: "poolish", shapeCount: null, preFermentCfg: null,
    },
    // ── Impasto base ──
    {
      id: "knead",
      title: "Impasto base",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 20,
      restDur: 0, restTemp: null,
      deps: [{ id: "poolish_ferm", wait: 1, grams: 1 }],
      kneadMethod: "hand",
      desc: "Versa il poolish, aggiungi farina, acqua, impasta. Aggiungi sale e olio dopo l'incordatura.",
      flours: [{ id: 0, type: "gt_00_for", g: 300, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 100, temp: null }],
      extras: [],
      yeasts: [],
      salts: [{ id: 0, type: "sale_fino", g: 10 }],
      sugars: [],
      fats: [{ id: 0, type: "olio_evo", g: 20 }],
      riseMethod: null, ovenCfg: null, sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
    // ── SPLIT: Dividi impasto 50/50 ──
    {
      id: "split",
      title: "Dividi impasto",
      type: "split",
      subtype: null,
      group: "Impasto",
      baseDur: 5,
      restDur: 0, restTemp: null,
      deps: [{ id: "knead", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Dividi l'impasto in due metà uguali.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
    // ── Ramo A: Pomodoro ──
    {
      id: "knead_a",
      title: "Impasto Pomodoro",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 5,
      restDur: 0, restTemp: null,
      deps: [{ id: "split", wait: 1, grams: 1 }],
      kneadMethod: "hand",
      desc: "Incorpora la polvere di pomodoro fino a colorazione uniforme.",
      flours: [], liquids: [],
      extras: [{ id: 0, name: "Polvere di pomodoro", g: 15 }],
      yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: "knead", shapeCount: null, preFermentCfg: null,
    },
    {
      id: "rise_a",
      title: "Lievitazione Pomodoro",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 60,
      restDur: 0, restTemp: null,
      deps: [{ id: "knead_a", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia lievitare 1 ora a temperatura ambiente.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: "room", ovenCfg: null, sourcePrep: "knead_a", shapeCount: null, preFermentCfg: null,
    },
    {
      id: "shape_a",
      title: "Forma filone rosso",
      type: "shape",
      subtype: null,
      group: "Impasto",
      baseDur: 5,
      restDur: 0, restTemp: null,
      deps: [{ id: "rise_a", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forma un filone lungo e uniforme.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: "knead_a", shapeCount: 1, preFermentCfg: null,
    },
    // ── Ramo B: Basilico ──
    {
      id: "knead_b",
      title: "Impasto Basilico",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 5,
      restDur: 0, restTemp: null,
      deps: [{ id: "split", wait: 1, grams: 1 }],
      kneadMethod: "hand",
      desc: "Incorpora la polvere di basilico fino a colorazione uniforme.",
      flours: [], liquids: [],
      extras: [{ id: 0, name: "Polvere di basilico", g: 10 }],
      yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: "knead", shapeCount: null, preFermentCfg: null,
    },
    {
      id: "rise_b",
      title: "Lievitazione Basilico",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 60,
      restDur: 0, restTemp: null,
      deps: [{ id: "knead_b", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia lievitare 1 ora a temperatura ambiente.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: "room", ovenCfg: null, sourcePrep: "knead_b", shapeCount: null, preFermentCfg: null,
    },
    {
      id: "shape_b",
      title: "Forma filone verde",
      type: "shape",
      subtype: null,
      group: "Impasto",
      baseDur: 5,
      restDur: 0, restTemp: null,
      deps: [{ id: "rise_b", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forma un filone lungo e uniforme.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: "knead_b", shapeCount: 1, preFermentCfg: null,
    },
    // ── JOIN: Intreccio ──
    {
      id: "braid",
      title: "Intreccia i filoni",
      type: "join",
      subtype: "braid",
      group: "Impasto",
      baseDur: 10,
      restDur: 0, restTemp: null,
      deps: [{ id: "shape_a", wait: 1, grams: 1 }, { id: "shape_b", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Sovrapponi i due filoni a croce e intreccia dal centro verso le estremità.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
    // ── 2ª Lievitazione ──
    {
      id: "rise2",
      title: "2ª Lievitazione",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 45,
      restDur: 0, restTemp: null,
      deps: [{ id: "braid", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia lievitare 45 minuti a temperatura ambiente.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: "room", ovenCfg: null, sourcePrep: "knead", shapeCount: null, preFermentCfg: null,
    },
    // ── Spennellatura ──
    {
      id: "brush",
      title: "Spennella con uovo",
      type: "pre_bake",
      subtype: "brush",
      group: "Impasto",
      baseDur: 2,
      restDur: 0, restTemp: null,
      deps: [{ id: "rise2", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Spennella la treccia con uovo sbattuto per doratura.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
    // ── Cottura ──
    {
      id: "bake",
      title: "Cottura",
      type: "bake",
      subtype: null,
      group: "Impasto",
      baseDur: 30,
      restDur: 0, restTemp: null,
      deps: [{ id: "brush", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forno preriscaldato a 200°C statico. Cottura 25-30 minuti fino a doratura.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null,
      ovenCfg: { panType: "stone", ovenType: "electric", ovenMode: "static", temp: 200, cieloPct: 50, shelfPosition: 2 },
      sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
    // ── Fine ──
    {
      id: "done",
      title: "Buon Appetito!",
      type: "done",
      subtype: null,
      group: "Impasto",
      baseDur: 0,
      restDur: 0, restTemp: null,
      deps: [{ id: "bake", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia raffreddare su griglia prima di tagliare.",
      flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
      riseMethod: null, ovenCfg: null, sourcePrep: null, shapeCount: null, preFermentCfg: null,
    },
  ],
}
