/**
 * Pizza con Funghi — 4 layers (Impasto, Sugo, Prep Funghi, Assemblaggio).
 *
 * More complex multi-layer recipe: three parallel prep tracks converge
 * into the final assembly layer. Demonstrates mushroom sauteing as a
 * separate prep layer with its own cooking steps.
 */

import type { RecipeV3 } from '@commons/types/recipe-layers'

export const RECIPE_ML_FUNGHI: RecipeV3 = {
  version: 3,
  meta: {
    name: 'Pizza ai Funghi Misti',
    author: 'KitchenPizza Zero',
    type: 'pizza',
    subtype: 'napoletana',
    locale: 'it',
  },
  ingredientGroups: ['Impasto', 'Sugo', 'Funghi', 'Assemblaggio'],
  layers: [
    // ── Layer 0: Impasto (poolish) ────────────────────────────
    {
      id: 'layer_impasto',
      type: 'impasto',
      name: 'Impasto con Poolish',
      color: '#F59E0B',
      icon: '\u{1F35E}',
      position: 0,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'impasto',
        config: {
          mode: 'ball',
          tray: { preset: 'teglia_40x30', l: 40, w: 30, h: 2, material: 'alu', griglia: false, count: 1 },
          ball: { weight: 280, count: 4 },
          thickness: 0.5,
          targetHyd: 68,
          doughHours: 30,
          yeastPct: 0.08,
          saltPct: 2.5,
          fatPct: 3,
          preImpasto: null,
          preFermento: 'poolish',
          flourMix: [],
          autoCorrect: false,
          reasoningLevel: 'medium',
        },
      },
      nodes: [
        {
          id: 'imp_poolish',
          type: 'pre_ferment',
          subtype: 'poolish',
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Poolish',
            desc: 'Prefermento liquido 12h',
            group: 'Impasto',
            baseDur: 720,
            restDur: 0,
            restTemp: 20,
            flours: [{ id: 1, type: 'gt_00_deb', g: 200, temp: null }],
            liquids: [{ id: 1, type: 'water', g: 200, temp: 20 }],
            extras: [],
            yeasts: [{ id: 1, type: 'fresh', g: 0.4 }],
            salts: [], sugars: [], fats: [],
            preFermentCfg: {
              preFermentPct: 40,
              hydrationPct: 100,
              yeastType: 'fresh',
              yeastPct: 0.2,
              fermentTemp: 20,
              fermentDur: 720,
              roomTempDur: null,
              starterForm: null,
            },
          },
        },
        {
          id: 'imp_dough',
          type: 'dough',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Impasto finale',
            desc: 'Aggiungere farina restante, acqua, sale, olio',
            group: 'Impasto',
            baseDur: 25,
            restDur: 0,
            restTemp: null,
            flours: [{ id: 1, type: 'gt_00_deb', g: 300, temp: null }],
            liquids: [{ id: 1, type: 'water', g: 140, temp: 20 }],
            extras: [],
            yeasts: [],
            salts: [{ id: 1, type: 'sale', g: 12.5 }],
            sugars: [],
            fats: [{ id: 1, type: 'olio_evo', g: 15 }],
            kneadMethod: 'hand',
          },
        },
        {
          id: 'imp_rise_room',
          type: 'rise',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Puntata',
            desc: '3 ore a temperatura ambiente',
            group: 'Impasto',
            baseDur: 180,
            restDur: 0,
            restTemp: 23,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            riseMethod: 'room',
          },
        },
        {
          id: 'imp_rise_fridge',
          type: 'rise',
          subtype: null,
          position: { x: 0, y: 450 },
          lane: 'main',
          data: {
            title: 'Maturazione in frigo',
            desc: '16-20 ore a 4\u00B0C',
            group: 'Impasto',
            baseDur: 1080,
            restDur: 0,
            restTemp: 4,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            riseMethod: 'fridge',
          },
        },
        {
          id: 'imp_shape',
          type: 'shape',
          subtype: null,
          position: { x: 0, y: 600 },
          lane: 'main',
          data: {
            title: 'Staglio',
            desc: 'Dividere in 4 panetti, appretto 2h',
            group: 'Impasto',
            baseDur: 15,
            restDur: 120,
            restTemp: 23,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            shapeCount: 4,
          },
        },
      ],
      edges: [
        { id: 'e_imp_1', source: 'imp_poolish', target: 'imp_dough', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_imp_2', source: 'imp_dough', target: 'imp_rise_room', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_imp_3', source: 'imp_rise_room', target: 'imp_rise_fridge', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_imp_4', source: 'imp_rise_fridge', target: 'imp_shape', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Panificazione', isMain: true, origin: { type: 'user' } }],
    },

    // ── Layer 1: Sugo ─────────────────────────────────────────
    {
      id: 'layer_sugo',
      type: 'sauce',
      name: 'Sugo pomodoro',
      color: '#EF4444',
      icon: '\u{1F345}',
      position: 1,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'sauce',
        config: {
          sauceType: 'pomodoro',
          targetVolume: 350,
          targetConsistency: 'medium',
          serving: 4,
          shelfLife: 3,
        },
      },
      nodes: [
        {
          id: 'sugo_ing',
          type: 'ingredient',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Pelati',
            desc: 'Pomodori pelati San Marzano',
            group: 'Sugo',
            baseDur: 3,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [], fats: [],
            extras: [{ id: 1, name: 'Pomodori pelati', g: 350 }],
          },
        },
        {
          id: 'sugo_cook',
          type: 'cook',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Cottura sugo',
            desc: 'Cuocere 15 min con aglio e basilico',
            group: 'Sugo',
            baseDur: 15,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], sugars: [],
            salts: [{ id: 1, type: 'sale', g: 3 }],
            fats: [{ id: 1, type: 'olio_evo', g: 15 }],
            extras: [
              { id: 1, name: 'Aglio', g: 5 },
              { id: 2, name: 'Basilico', g: 5 },
            ],
            cookMethod: 'pan',
            cookTemp: 90,
          },
        },
        {
          id: 'sugo_blend',
          type: 'blend',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Passare',
            desc: 'Frullare e filtrare',
            group: 'Sugo',
            baseDur: 5,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
          },
        },
      ],
      edges: [
        { id: 'e_sugo_1', source: 'sugo_ing', target: 'sugo_cook', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_sugo_2', source: 'sugo_cook', target: 'sugo_blend', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Sugo', isMain: true, origin: { type: 'user' } }],
    },

    // ── Layer 2: Prep Funghi ──────────────────────────────────
    {
      id: 'layer_funghi',
      type: 'prep',
      name: 'Preparazione Funghi',
      color: '#78716C',
      icon: '\u{1F344}',
      position: 2,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'prep',
        config: {
          prepType: 'verdure',
          servings: 4,
          yield: 350,
        },
      },
      nodes: [
        {
          id: 'fun_ing',
          type: 'ingredient',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Funghi misti',
            desc: 'Champignon, porcini, chiodini',
            group: 'Funghi',
            baseDur: 5,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [], fats: [],
            extras: [
              { id: 1, name: 'Champignon', g: 200 },
              { id: 2, name: 'Porcini', g: 100 },
              { id: 3, name: 'Chiodini', g: 100 },
            ],
          },
        },
        {
          id: 'fun_wash',
          type: 'wash',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Pulire i funghi',
            desc: 'Spazzolare e tagliare le basi terrose',
            group: 'Funghi',
            baseDur: 10,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
          },
        },
        {
          id: 'fun_cut',
          type: 'cut',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Affettare',
            desc: 'Fette spesse 3-4mm',
            group: 'Funghi',
            baseDur: 8,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            cutStyle: 'slice',
          },
        },
        {
          id: 'fun_cook',
          type: 'cook',
          subtype: null,
          position: { x: 0, y: 450 },
          lane: 'main',
          data: {
            title: 'Saltare in padella',
            desc: 'Fuoco alto con aglio e prezzemolo, 8 min',
            group: 'Funghi',
            baseDur: 8,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], sugars: [],
            salts: [{ id: 1, type: 'sale', g: 2 }],
            fats: [{ id: 1, type: 'olio_evo', g: 15 }],
            extras: [
              { id: 1, name: 'Aglio', g: 5 },
              { id: 2, name: 'Prezzemolo', g: 3 },
            ],
            cookMethod: 'pan',
            cookTemp: 200,
          },
        },
      ],
      edges: [
        { id: 'e_fun_1', source: 'fun_ing', target: 'fun_wash', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_fun_2', source: 'fun_wash', target: 'fun_cut', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_fun_3', source: 'fun_cut', target: 'fun_cook', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Funghi', isMain: true, origin: { type: 'user' } }],
    },

    // ── Layer 3: Assemblaggio ─────────────────────────────────
    {
      id: 'layer_assembly',
      type: 'prep',
      name: 'Assemblaggio e Cottura',
      color: '#8B5CF6',
      icon: '\u{1F355}',
      position: 3,
      visible: true,
      locked: false,
      masterConfig: {
        type: 'prep',
        config: {
          prepType: 'assemblaggio',
          servings: 4,
          yield: 1200,
        },
      },
      nodes: [
        {
          id: 'asm_base',
          type: 'assemble',
          subtype: null,
          position: { x: 0, y: 0 },
          lane: 'main',
          data: {
            title: 'Base: impasto + sugo',
            desc: 'Stendere il disco, condire con sugo e mozzarella',
            group: 'Assemblaggio',
            baseDur: 8,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [], fats: [],
            extras: [
              { id: 1, name: 'Mozzarella fior di latte', g: 400 },
            ],
            applicationMethod: 'topping',
            applicationTiming: 'pre_bake',
          },
        },
        {
          id: 'asm_bake',
          type: 'cook',
          subtype: null,
          position: { x: 0, y: 150 },
          lane: 'main',
          data: {
            title: 'Prima cottura',
            desc: '400\u00B0C per 3 minuti — solo base e mozzarella',
            group: 'Assemblaggio',
            baseDur: 3,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            cookMethod: 'oven',
            cookTemp: 400,
          },
        },
        {
          id: 'asm_funghi',
          type: 'garnish',
          subtype: null,
          position: { x: 0, y: 300 },
          lane: 'main',
          data: {
            title: 'Aggiungere funghi',
            desc: 'Distribuire i funghi saltati sulla pizza calda',
            group: 'Assemblaggio',
            baseDur: 2,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], extras: [], yeasts: [], salts: [], sugars: [], fats: [],
            applicationMethod: 'topping',
            applicationTiming: 'post_bake',
          },
        },
        {
          id: 'asm_plate',
          type: 'plate',
          subtype: null,
          position: { x: 0, y: 450 },
          lane: 'main',
          data: {
            title: 'Impiattare',
            desc: 'Filo d\'olio, prezzemolo fresco',
            group: 'Assemblaggio',
            baseDur: 2,
            restDur: 0,
            restTemp: null,
            flours: [], liquids: [], yeasts: [], salts: [], sugars: [],
            fats: [{ id: 1, type: 'olio_evo', g: 10 }],
            extras: [{ id: 1, name: 'Prezzemolo', g: 3 }],
          },
        },
      ],
      edges: [
        { id: 'e_asm_1', source: 'asm_base', target: 'asm_bake', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_asm_2', source: 'asm_bake', target: 'asm_funghi', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
        { id: 'e_asm_3', source: 'asm_funghi', target: 'asm_plate', data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 } },
      ],
      lanes: [{ id: 'main', label: 'Assemblaggio', isMain: true, origin: { type: 'user' } }],
    },
  ],

  crossEdges: [
    // Impasto -> Assembly base
    {
      id: 'xedge_imp_shape__asm_base',
      sourceLayerId: 'layer_impasto',
      sourceNodeId: 'imp_shape',
      targetLayerId: 'layer_assembly',
      targetNodeId: 'asm_base',
      label: 'impasto pronto',
      data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 },
    },
    // Sugo -> Assembly base
    {
      id: 'xedge_sugo_blend__asm_base',
      sourceLayerId: 'layer_sugo',
      sourceNodeId: 'sugo_blend',
      targetLayerId: 'layer_assembly',
      targetNodeId: 'asm_base',
      label: 'sugo pronto',
      data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 },
    },
    // Funghi -> Assembly garnish (post-bake)
    {
      id: 'xedge_fun_cook__asm_funghi',
      sourceLayerId: 'layer_funghi',
      sourceNodeId: 'fun_cook',
      targetLayerId: 'layer_assembly',
      targetNodeId: 'asm_funghi',
      label: 'funghi pronti',
      data: { scheduleTimeRatio: 1, scheduleQtyRatio: 1 },
    },
  ],
}
