export interface LlmPromptEntry {
  key: string
  labelKey: string
  descriptionKey: string
  category: 'explanation' | 'constraint' | 'compatibility' | 'verification'
  template: string
  variables: string[]
  defaultModel?: string
  lastModified: string
}

// Default templates — used as reset targets in admin panel
const DEFAULT_TEMPLATES: Record<string, string> = {
  explain_warning: `You are a culinary science expert. Explain the following recipe warning in simple, practical terms.

Warning: {{messageKey}}
Context: {{context}}
Locale: {{locale}}

Provide a brief explanation (2-3 sentences) of why this warning matters and what the user should do.
Respond in the language specified by the locale.`,

  nl_to_constraints: `You are a recipe adaptation assistant. Extract structured constraints from the user's natural language request.

User request: "{{userInput}}"
Current recipe: {{recipeSummary}}

Extract constraints as JSON with these optional fields:
{
  "targetHydration": number | null,
  "targetDoughHours": number | null,
  "flourTypes": string[] | null,
  "ovenType": string | null,
  "maxTemp": number | null,
  "deadline": string | null,
  "servings": number | null,
  "notes": string | null
}

Return ONLY the JSON object.`,

  cross_layer_compat: `You are a culinary science expert. Assess the compatibility of combining these two recipe layers.

Layer 1: {{layer1Summary}}
Layer 2: {{layer2Summary}}

Respond as JSON:
{
  "compatible": boolean,
  "score": number (0-100),
  "reasoning": string,
  "suggestions": string[]
}`,

  verify_reconciliation: `You are a culinary science verification system. RESPOND IN {{locale}} LANGUAGE ONLY.

RULES:
- You can ONLY choose from actions already generated by the science engine
- Keep llmReason to 1 short sentence in {{locale}} language
- Only include verifiedWarnings for warnings you have an opinion on
- If you are NOT SURE about a warning, respond with "confirmed" (trust the science)
- Do NOT guess or hallucinate. If you don't know the culinary science behind a warning, say "confirmed"
- Only downgrade/upgrade/dismiss when you are CERTAIN based on culinary knowledge
- For each warning, you MUST provide a verdict. Do not skip warnings.

Recipe: {{recipeSummary}}
Type: {{recipeType}}/{{recipeSubtype}}
Values: hyd={{hydration}}%, yeast={{yeastPct}}%, salt={{saltPct}}%, W={{flourW}}, hours={{doughHours}}

Warnings:
{{warningsSummary}}

Respond as JSON:
{"verifiedWarnings":[{"warningId":"id","llmVerdict":"confirmed|downgraded|upgraded|dismissed","llmReason":"short reason in {{locale}}","suggestedAction":0}],"additionalInsights":[],"autoActions":[{"warningId":"id","actionIndex":0,"confidence":0.9}]}`,
}

export const LLM_PROMPTS: LlmPromptEntry[] = [
  {
    key: 'explain_warning',
    labelKey: 'admin.ai.prompt.explain_warning',
    descriptionKey: 'admin.ai.prompt.explain_warning_desc',
    category: 'explanation',
    template: DEFAULT_TEMPLATES.explain_warning,
    variables: ['messageKey', 'context', 'locale'],
    lastModified: '2026-03-31',
  },
  {
    key: 'nl_to_constraints',
    labelKey: 'admin.ai.prompt.nl_to_constraints',
    descriptionKey: 'admin.ai.prompt.nl_to_constraints_desc',
    category: 'constraint',
    template: DEFAULT_TEMPLATES.nl_to_constraints,
    variables: ['userInput', 'recipeSummary'],
    lastModified: '2026-03-31',
  },
  {
    key: 'cross_layer_compat',
    labelKey: 'admin.ai.prompt.cross_layer_compat',
    descriptionKey: 'admin.ai.prompt.cross_layer_compat_desc',
    category: 'compatibility',
    template: DEFAULT_TEMPLATES.cross_layer_compat,
    variables: ['layer1Summary', 'layer2Summary'],
    lastModified: '2026-03-31',
  },
  {
    key: 'verify_reconciliation',
    labelKey: 'admin.ai.prompt.verify_reconciliation',
    descriptionKey: 'admin.ai.prompt.verify_reconciliation_desc',
    category: 'verification',
    template: DEFAULT_TEMPLATES.verify_reconciliation,
    variables: ['recipeSummary', 'recipeType', 'recipeSubtype', 'hydration', 'yeastPct', 'saltPct', 'flourW', 'doughHours', 'warningsSummary', 'locale'],
    lastModified: '2026-03-31',
  },
]

export { DEFAULT_TEMPLATES }
