import type { Recipe } from '@commons/types/recipe'

/**
 * Pizza Bianca in Teglia alla Romana
 *
 * Tray: 60×40 cm professional pan (2400 cm²)
 * Target weight: ~1300g (coefficient 0.54 × 2400 cm²)
 * Hydration: 80%
 * Flour: 0 forte W 300 (gt_0_for)
 *
 * Calculations:
 *   totalFlour = 1300 / (1 + 0.80 + 0.025 + 0.05 + 0.003 + 0.0015) ≈ 693g
 *   water      = 693 × 0.80  ≈ 555g
 *   salt       = 693 × 0.025 ≈ 17g
 *   oil        = 693 × 0.05  ≈ 35g
 *   malto      = 693 × 0.003 ≈ 2g
 *   yeast      = 693 × 0.0015 ≈ 1g
 */
export const RECIPE_3: Recipe = {
  meta: {
    name: "Pizza Bianca in Teglia alla Romana",
    author: "KitchenPizza",
    type: "pizza",
    subtype: "teglia_romana",
  },
  portioning: {
    mode: "tray",
    tray: {
      preset: "teglia_60x40",
      l: 60,
      w: 40,
      h: 3,
      material: "alluminio",
      griglia: false,
      count: 1,
    },
    ball: { weight: 250, count: 4 },
    thickness: 0.54,
    targetHyd: 80,
  },
  ingredientGroups: ["Impasto"],
  steps: [
    // Step 1: Autolisi
    {
      id: "autolisi",
      title: "Autolisi",
      type: "pre_dough",
      subtype: "autolisi",
      group: "Impasto",
      baseDur: 30,
      restDur: 0,
      restTemp: null,
      deps: [],
      kneadMethod: null,
      desc: "Mescola farina e acqua (80% del totale). Lascia riposare coperto 30 minuti.",
      flours: [{ id: 0, type: "gt_0_for", g: 693, temp: null }],
      liquids: [{ id: 0, type: "Acqua", g: 444, temp: null }],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 2: Impasto
    {
      id: "knead",
      title: "Impasto",
      type: "dough",
      subtype: "hand",
      group: "Impasto",
      baseDur: 15,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "autolisi", wait: 1, grams: 1 }],
      kneadMethod: "hand",
      desc: "Aggiungi sale, malto, lievito e impasta. Dopo l'incordatura aggiungi olio e acqua rimanente a filo.",
      flours: [],
      liquids: [{ id: 0, type: "Acqua", g: 111, temp: null }],
      extras: [],
      yeasts: [{ id: 0, type: "fresh", g: 1 }],
      salts: [{ id: 0, type: "sale_fino", g: 17 }],
      sugars: [{ id: 0, type: "malto_d", g: 2 }],
      fats: [{ id: 0, type: "olio_evo", g: 35 }],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 3: Puntata in Massa
    {
      id: "r1",
      title: "Puntata in Massa",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 60,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "knead", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Copri e lascia puntare a temperatura ambiente per 1 ora con pieghe ogni 20 minuti.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 4: Maturazione in Frigo
    {
      id: "cold",
      title: "Maturazione in Frigo",
      type: "rise",
      subtype: "fridge",
      group: "Impasto",
      baseDur: 1080,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r1", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Poni l'impasto in contenitore oliato e chiuso in frigo a 3-4°C per 18-24 ore.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "fridge",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 5: Stesura in Teglia
    {
      id: "shape",
      title: "Stesura in Teglia",
      type: "shape",
      subtype: null,
      group: "Impasto",
      baseDur: 10,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "cold", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Rovescia l'impasto sulla teglia oliata. Schiaccia senza tirare fino a coprire l'intera area.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: 1,
      preFermentCfg: null,
    },
    // Step 6: Lievitazione in Teglia
    {
      id: "r2",
      title: "Lievitazione in Teglia",
      type: "rise",
      subtype: "room",
      group: "Impasto",
      baseDur: 90,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "shape", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Lascia lievitare in teglia coperta fino al raddoppio (1-2 ore a TA).",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: "room",
      ovenCfg: null,
      sourcePrep: "knead",
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 7: Condimento Superficie
    {
      id: "topping",
      title: "Condimento Superficie",
      type: "pre_bake",
      subtype: "topping",
      group: "Impasto",
      baseDur: 5,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "r2", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Fora delicatamente con le dita. Condisci con olio EVO e sale Maldon in superficie.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [{ id: 0, type: "sale_maldon", g: 3 }],
      sugars: [],
      fats: [{ id: 0, type: "olio_evo", g: 15 }],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 8: Cottura
    {
      id: "bake",
      title: "Cottura",
      type: "bake",
      subtype: null,
      group: "Impasto",
      baseDur: 9,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "topping", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Forno preriscaldato a 250°C. Platea 280°C, cielo 240°C. Cottura 8-10 minuti.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: {
        panType: "alluminio",
        ovenType: "electric",
        ovenMode: "static",
        temp: 250,
        cieloPct: 40,
        shelfPosition: 2,
      },
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
    // Step 9: Done
    {
      id: "done",
      title: "Buon Appetito!",
      type: "done",
      subtype: null,
      group: "Impasto",
      baseDur: 0,
      restDur: 0,
      restTemp: null,
      deps: [{ id: "bake", wait: 1, grams: 1 }],
      kneadMethod: null,
      desc: "Sforna e lascia raffreddare leggermente. Taglia a tranci.",
      flours: [],
      liquids: [],
      extras: [],
      yeasts: [],
      salts: [],
      sugars: [],
      fats: [],
      riseMethod: null,
      ovenCfg: null,
      sourcePrep: null,
      shapeCount: null,
      preFermentCfg: null,
    },
  ],
}
