import type { StepTypeEntry, ColorMapEntry } from '@commons/types/recipe'

export const STEP_TYPES: StepTypeEntry[] = [
  {
    key: "pre_dough",
    labelKey: "step_pre_dough",
    icon: "🧪",
    subtypes: [
      { key: "tangzhong", labelKey: "step_subtype_tangzhong", defaults: { baseDur: 5, liquidTemp: 95, flourPctOfLiquid: 1.5, flourPctOfLiquidMax: 2 } },
      { key: "autolisi", labelKey: "step_subtype_autolisi", defaults: { baseDur: 30, hydrationPct: 55, useMainDoughFlour: true } },
    ],
  },
  {
    key: "pre_ferment",
    labelKey: "step_pre_ferment",
    icon: "🫧",
    subtypes: [
      { key: "biga", labelKey: "step_subtype_biga", defaults: { phases: 2, preFermentPct: 45, preFermentPctRange: [30, 100], hydrationPct: 44, hydrationPctRange: [43, 50], yeastType: "fresh", yeastPct: 1, yeastPctRange: [0.8, 1.5], fermentTemp: 18, fermentTempRange: [16, 20], fermentDur: 1080, fermentDurRange: [960, 1440], phaseDescriptionKeys: ["phase_biga_1", "phase_biga_2"] } },
      { key: "poolish", labelKey: "step_subtype_poolish", defaults: { phases: 2, preFermentPct: 40, preFermentPctRange: [20, 60], hydrationPct: 100, hydrationLocked: true, hydrationPctRange: [100, 100], yeastType: "fresh", yeastPct: 0.1, yeastPctRange: [0.05, 1.5], fermentTemp: 20, fermentTempRange: [18, 24], fermentDur: 720, fermentDurRange: [120, 960], phaseDescriptionKeys: ["phase_poolish_1", "phase_poolish_2"] } },
      { key: "sponge", labelKey: "step_subtype_sponge", defaults: { phases: 2, preFermentPct: 60, preFermentPctRange: [40, 75], hydrationPct: 60, hydrationPctRange: [55, 70], yeastType: "fresh", yeastPct: 1.5, yeastPctRange: [1, 3], fermentTemp: 25, fermentTempRange: [22, 28], fermentDur: 120, fermentDurRange: [60, 240], phaseDescriptionKeys: ["phase_sponge_1", "phase_sponge_2"] } },
      { key: "idrobiga", labelKey: "step_subtype_idrobiga", defaults: { phases: 2, preFermentPct: 45, preFermentPctRange: [30, 100], hydrationPct: 75, hydrationPctRange: [70, 80], yeastType: "fresh", yeastPct: 1, yeastPctRange: [0.8, 1.2], roomTempDur: 120, roomTempRange: [90, 180], roomTemp: 20, fermentTemp: 4, fermentTempRange: [2, 6], fermentDur: 1320, fermentDurRange: [1200, 1440], phaseDescriptionKeys: ["phase_idrobiga_1", "phase_idrobiga_2"] } },
      { key: "sourdough", labelKey: "step_subtype_sourdough", defaults: { phases: 1, preFermentPct: 25, preFermentPctRange: [15, 100], hydrationPct: 50, hydrationPctRange: [45, 130], yeastType: null, yeastPct: null, starterForms: ["solid", "licoli"], phaseDescriptionKeys: ["phase_sourdough_1"] } },
      { key: "old_dough", labelKey: "step_subtype_old_dough", defaults: { phases: 1, preFermentPct: 20, preFermentPctRange: [10, 100], hydrationPct: 60, hydrationPctRange: [50, 75], yeastType: null, yeastPct: null, maxAgeDays: 3, phaseDescriptionKeys: ["phase_old_dough_1"] } },
    ],
  },
  {
    key: "dough",
    labelKey: "step_dough",
    icon: "🖐️",
    subtypes: [
      { key: "hand", labelKey: "step_subtype_hand", defaults: { kneadMethod: "hand" } },
      { key: "stand", labelKey: "step_subtype_stand", defaults: { kneadMethod: "stand" } },
      { key: "spiral", labelKey: "step_subtype_spiral", defaults: { kneadMethod: "spiral" } },
    ],
  },
  { key: "rest", labelKey: "step_rest", icon: "❄️" },
  {
    key: "rise",
    labelKey: "step_rise",
    icon: "⏳",
    subtypes: [
      { key: "room", labelKey: "step_subtype_room", defaults: { riseMethod: "room" } },
      { key: "fridge", labelKey: "step_subtype_fridge", defaults: { riseMethod: "fridge" } },
      { key: "ctrl18", labelKey: "step_subtype_ctrl18", defaults: { riseMethod: "ctrl18" } },
      { key: "ctrl12", labelKey: "step_subtype_ctrl12", defaults: { riseMethod: "ctrl12" } },
    ],
  },
  { key: "shape", labelKey: "step_shape", icon: "🔄" },
  {
    key: "pre_bake",
    labelKey: "step_pre_bake",
    icon: "✨",
    subtypes: [
      { key: "brush", labelKey: "step_subtype_brush", defaults: { baseDur: 5 } },
      { key: "topping", labelKey: "step_subtype_topping", defaults: { baseDur: 5 } },
      { key: "scoring", labelKey: "step_subtype_scoring", defaults: { baseDur: 3 } },
      { key: "boil", labelKey: "step_subtype_boil", defaults: { baseDur: 2 } },
      { key: "dock", labelKey: "step_subtype_dock", defaults: { baseDur: 2 } },
      { key: "flour_dust", labelKey: "step_subtype_flour_dust", defaults: { baseDur: 1 } },
      { key: "oil_coat", labelKey: "step_subtype_oil_coat", defaults: { baseDur: 2 } },
      { key: "steam_inject", labelKey: "step_subtype_steam_inject", defaults: { baseDur: 1 } },
      { key: "generic", labelKey: "step_subtype_generic", defaults: {} },
    ],
  },
  {
    key: "bake",
    labelKey: "step_bake",
    icon: "🔥",
    subtypes: [
      { key: "forno", labelKey: "step_subtype_forno", defaults: { baseDur: 30 } },
      { key: "pentola", labelKey: "step_subtype_pentola", defaults: { baseDur: 40 } },
      { key: "vapore", labelKey: "step_subtype_vapore", defaults: { baseDur: 15 } },
      { key: "frittura", labelKey: "step_subtype_frittura", defaults: { baseDur: 5 } },
      { key: "aria", labelKey: "step_subtype_aria", defaults: { baseDur: 10 } },
      { key: "griglia", labelKey: "step_subtype_griglia", defaults: { baseDur: 8 } },
      { key: "padella", labelKey: "step_subtype_padella", defaults: { baseDur: 8 } },
    ],
  },
  {
    key: "post_bake",
    labelKey: "step_post_bake",
    icon: "🍽️",
    subtypes: [
      { key: "garnish", labelKey: "step_subtype_garnish", defaults: { baseDur: 5 } },
      { key: "fill", labelKey: "step_subtype_fill", defaults: { baseDur: 10 } },
      { key: "glaze", labelKey: "step_subtype_glaze", defaults: { baseDur: 5 } },
      { key: "dress", labelKey: "step_subtype_dress", defaults: { baseDur: 3 } },
      { key: "dust", labelKey: "step_subtype_dust", defaults: { baseDur: 2 } },
      { key: "plate", labelKey: "step_subtype_plate", defaults: { baseDur: 5 } },
      { key: "generic", labelKey: "step_subtype_generic", defaults: {} },
    ],
  },
  { key: "done", labelKey: "step_done", icon: "🎉" },
  {
    key: "prep",
    labelKey: "step_prep",
    icon: "🔪",
    subtypes: [
      { key: "cut", labelKey: "step_subtype_cut", defaults: { baseDur: 10 } },
      { key: "cook", labelKey: "step_subtype_cook", defaults: { baseDur: 15 } },
      { key: "mix", labelKey: "step_subtype_mix", defaults: { baseDur: 5 } },
      { key: "marinate", labelKey: "step_subtype_marinate", defaults: { baseDur: 120 } },
      { key: "ferment", labelKey: "step_subtype_ferment", defaults: { baseDur: 4320 } },
      { key: "cool", labelKey: "step_subtype_cool", defaults: { baseDur: 30 } },
      { key: "assemble", labelKey: "step_subtype_assemble", defaults: { baseDur: 10 } },
    ],
  },
  { key: "split", labelKey: "step_split", icon: "✂️" },
  {
    key: "join",
    labelKey: "step_join",
    icon: "🔗",
    subtypes: [
      { key: "braid", labelKey: "step_subtype_braid", defaults: { baseDur: 10 } },
      { key: "layer", labelKey: "step_subtype_layer", defaults: { baseDur: 5 } },
      { key: "fold", labelKey: "step_subtype_fold", defaults: { baseDur: 5 } },
      { key: "enclose", labelKey: "step_subtype_enclose", defaults: { baseDur: 10 } },
      { key: "mix", labelKey: "step_subtype_mix", defaults: { baseDur: 5 } },
      { key: "side_by_side", labelKey: "step_subtype_side_by_side", defaults: { baseDur: 3 } },
      { key: "generic", labelKey: "step_subtype_generic", defaults: {} },
    ],
  },
]

export const COLOR_MAP: Record<string, ColorMapEntry> = {
  pre_dough: { bgVar: "step-pre-dough-bg", txVar: "step-pre-dough-tx", lbKey: "colormap_pre_dough_lb" },
  pre_ferment: { bgVar: "step-pre-ferment-bg", txVar: "step-pre-ferment-tx", lbKey: "colormap_pre_ferment_lb" },
  dough: { bgVar: "step-dough-bg", txVar: "step-dough-tx", lbKey: "colormap_dough_lb" },
  rest: { bgVar: "step-rest-bg", txVar: "step-rest-tx", lbKey: "colormap_rest_lb" },
  rise: { bgVar: "step-rise-bg", txVar: "step-rise-tx", lbKey: "colormap_rise_lb" },
  shape: { bgVar: "step-shape-bg", txVar: "step-shape-tx", lbKey: "colormap_shape_lb" },
  pre_bake: { bgVar: "step-pre-bake-bg", txVar: "step-pre-bake-tx", lbKey: "colormap_pre_bake_lb" },
  bake: { bgVar: "step-bake-bg", txVar: "step-bake-tx", lbKey: "colormap_bake_lb" },
  done: { bgVar: "step-done-bg", txVar: "step-done-tx", lbKey: "colormap_done_lb" },
  post_bake: { bgVar: "step-post-bake-bg", txVar: "step-post-bake-tx", lbKey: "colormap_post_bake_lb" },
  prep: { bgVar: "step-prep-bg", txVar: "step-prep-tx", lbKey: "colormap_prep_lb" },
  split: { bgVar: "step-split-bg", txVar: "step-split-tx", lbKey: "colormap_split_lb" },
  join: { bgVar: "step-join-bg", txVar: "step-join-tx", lbKey: "colormap_join_lb" },
}
