import type { TrayPreset, TrayMaterial } from '@commons/types/recipe'

export const TRAY_PRESETS = [
  {
    key: "terrina_29",
    labelKey: "tray_terrina_29",
    l: 29,
    w: 8.5,
    h: 9,
    material: "ci_lid",
    griglia: false,
  },
  {
    key: "plumcake_25",
    labelKey: "tray_plumcake_25",
    l: 25,
    w: 11,
    h: 7,
    material: "alu",
    griglia: false,
  },
  {
    key: "plumcake_30",
    labelKey: "tray_plumcake_30",
    l: 30,
    w: 11,
    h: 7,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_40x30",
    labelKey: "tray_teglia_40x30",
    l: 40,
    w: 30,
    h: 2,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_30x30",
    labelKey: "tray_teglia_30x30",
    l: 30,
    w: 30,
    h: 6,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_60x40",
    labelKey: "tray_teglia_60x40",
    l: 60,
    w: 40,
    h: 2,
    material: "steel",
    griglia: false,
  },
  {
    key: "tonda_28",
    labelKey: "tray_tonda_28",
    l: 28,
    w: 28,
    h: 3,
    material: "alu",
    griglia: false,
  },
  {
    key: "tonda_32",
    labelKey: "tray_tonda_32",
    l: 32,
    w: 32,
    h: 3,
    material: "alu",
    griglia: false,
  },
  {
    key: "ferro_blue",
    labelKey: "tray_ferro_blue",
    l: 40,
    w: 30,
    h: 2.5,
    material: "steel",
    griglia: false,
  },
] as const satisfies ReadonlyArray<TrayPreset>

export const TRAY_MATERIALS = [
  { key: "ci_lid", labelKey: "tray_mat_ci_lid", bMin: 35, bMax: 40, defTemp: 170, hasVent: true },
  { key: "ci_no", labelKey: "tray_mat_ci_no", bMin: 30, bMax: 35, defTemp: 170, hasVent: false },
  { key: "alu", labelKey: "tray_mat_alu", bMin: 30, bMax: 40, defTemp: 180, hasVent: false },
  { key: "glass", labelKey: "tray_mat_glass", bMin: 35, bMax: 45, defTemp: 175, hasVent: false },
  { key: "steel", labelKey: "tray_mat_steel", bMin: 30, bMax: 40, defTemp: 180, hasVent: false },
  { key: "copper", labelKey: "tray_mat_copper", bMin: 28, bMax: 35, defTemp: 175, hasVent: false },
  { key: "stone", labelKey: "tray_mat_stone", bMin: 25, bMax: 35, defTemp: 250, hasVent: false },
] as const satisfies ReadonlyArray<TrayMaterial>
