import type { TrayPreset, TrayMaterial } from '@commons/types/recipe'

export const TRAY_PRESETS = [
  {
    key: "terrina_29",
    label: "Terrina 29×8.5×9",
    l: 29,
    w: 8.5,
    h: 9,
    material: "ci_lid",
    griglia: false,
  },
  {
    key: "plumcake_25",
    label: "Plumcake 25×11×7",
    l: 25,
    w: 11,
    h: 7,
    material: "alu",
    griglia: false,
  },
  {
    key: "plumcake_30",
    label: "Plumcake 30×11×7",
    l: 30,
    w: 11,
    h: 7,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_40x30",
    label: "Teglia 40×30×2",
    l: 40,
    w: 30,
    h: 2,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_30x30",
    label: "Teglia 30×30×6",
    l: 30,
    w: 30,
    h: 6,
    material: "alu",
    griglia: false,
  },
  {
    key: "teglia_60x40",
    label: "Teglia 60×40×2",
    l: 60,
    w: 40,
    h: 2,
    material: "steel",
    griglia: false,
  },
  {
    key: "tonda_28",
    label: "Tonda Ø28×3",
    l: 28,
    w: 28,
    h: 3,
    material: "alu",
    griglia: false,
  },
  {
    key: "tonda_32",
    label: "Tonda Ø32×3",
    l: 32,
    w: 32,
    h: 3,
    material: "alu",
    griglia: false,
  },
  {
    key: "ferro_blue",
    label: "Ferro blu 40×30×2.5",
    l: 40,
    w: 30,
    h: 2.5,
    material: "steel",
    griglia: false,
  },
] as const satisfies ReadonlyArray<TrayPreset>

export const TRAY_MATERIALS = [
  {
    key: "ci_lid",
    label: "Ghisa con coperchio",
    bMin: 35,
    bMax: 40,
    defTemp: 170,
  },
  { key: "ci_no", label: "Ghisa", bMin: 30, bMax: 35, defTemp: 170 },
  { key: "alu", label: "Alluminio", bMin: 30, bMax: 40, defTemp: 180 },
  { key: "glass", label: "Vetro / Pirex", bMin: 35, bMax: 45, defTemp: 175 },
  { key: "steel", label: "Acciaio", bMin: 30, bMax: 40, defTemp: 180 },
  { key: "copper", label: "Rame", bMin: 28, bMax: 35, defTemp: 175 },
  {
    key: "stone",
    label: "Pietra refrattaria",
    bMin: 25,
    bMax: 35,
    defTemp: 250,
  },
] as const satisfies ReadonlyArray<TrayMaterial>
